type: plm
name: bert_softmax
delimiter: "\t"
input: "resources/data/dataset/ner/zh/ccks/address/bio"
file_format: conll
output: "resources/data/output/ner/zh/ccks/address/bio/bert_softmax/bio"
max_length: 50
model_path: resources/data/pretrained/bert_base_chinese
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
plm_lr: 3.0e-5
not_plm_lr: 3.0e-5
weight_decay: 0.0
model_type: bert
decode_type: general
num_train_epochs: 10
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
seed: 100
do_lower_case: True
task_name: ner
cpu: True
