type: BERT
name: BERT_Softmax
delimiter: "\t"
input: "resources/data/dataset/ner/zh/cluener/bio"
output: "resources/data/output/ner/zh/cluener/bert"
max_length: 128
pad_to_max_length: True
model_path: resources/data/pretrained/bert_base_chinese
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5.0e-5
weight_decay: 0.0
num_train_epochs: 3
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
seed: 100
label_all_tokens: True
do_lower_case: True
task_name: ner
return_entity_level_metrics: True
