type: plm
name: bert_crf
delimiter: "\t"
input: "resources/data/dataset/ner/zh/ccks/address/bies/"
file_format: bies
output: "resources/data/output/ner/zh/ccks/address/bies/bert_crf/"
summary: "resources/data/output/ner/zh/ccks/address/bies/bert_crf/summary"
max_length: 60
model_path: resources/data/pretrained/bert-base-chinese
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
plm_lr: 3.0e-5
not_plm_lr: 5.0e-3
weight_decay: 0.0
model_type: bert
decode_type: general
num_train_epochs: 10
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
seed: 100
do_lower_case: True
task_name: ner
cpu: False
