type: plm
name: bert_biaffine
delimiter: "\t"
input: "resources/data/dataset/ner/zh/ccks/address/json"
file_format: biaffine
output: "resources/data/output/ner/zh/ccks/address/bio/bert_biaffine/json"
max_length: 50
model_path: resources/data/pretrained/bert_base_chinese
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
plm_lr: 3.0e-5
not_plm_lr: 5.0e-5
weight_decay: 0.0
model_type: bert
decode_type: biaffine
num_train_epochs: 30
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
seed: 100
do_lower_case: True
task_name: ner
