tf_checkpoint_path: "data/pretrained/bert_base_chinese/bert_model.ckpt"
bert_config_file: "data/pretrained/bert_base_chinese/bert_config.json"
pytorch_dump_path: "data/pretrained/bert_base_chinese/model.pt"
