dict:
  prov: "resources/data/dict/address/txt/prov.txt"
  city: "resources/data/dict/address/txt/city.txt"
  district: "resources/data/dict/address/txt/district.txt"
  town: "resources/data/dict/address/txt/town.txt"
  community: "resources/data/dict/address/txt/community.txt"
plm:
  name: Bert_Biaffine
  decode_type: biaffine
  max_length: 50
  model_path: "resources/data/output/ner/zh/ccks/address/bio/bert_biaffine/json/many"
  do_lower_case: True
  device: cuda
 