# dict:
#   prov: "resources/data/dict/address/txt/prov.txt"
#   city: "resources/data/dict/address/txt/city.txt"
#   district: "resources/data/dict/address/txt/district.txt"
#   town: "resources/data/dict/address/txt/town.txt"
#   community: "resources/data/dict/address/txt/community.txt"
plm:
  name: bert_crf
  decode_type: general
  max_length: 50
  model_path: "resources/data/output/ner/zh/ccks/address/bio/bert_crf/bio"
  do_lower_case: True
  device: cuda
 