dict:
  prov: "resources/data/dict/address/clean/prov.txt"
  city: "resources/data/dict/address/clean/city.txt"
  district: "resources/data/dict/address/clean/district.txt"
  town: "resources/data/dict/address/clean/town.txt"
  community: "resources/data/dict/address/clean/community.txt"
plm:
  name: bert_lstm_crf
  decode_type: general
  max_length: 60
  model_path: "resources/data/output/ner/zh/ccks/address/bio/bert_lstm_crf/"
  do_lower_case: True
  device: cuda
 