dict:
  prov: "resources/data/dict/address/clean/prov.txt"
  city: "resources/data/dict/address/clean/city.txt"
  district: "resources/data/dict/address/clean/district.txt"
  town: "resources/data/dict/address/clean/town.txt"
  community: "resources/data/dict/address/clean/community.txt"
plm:
  name: bert_biaffine
  decode_type: biaffine
  max_length: 100
  model_path: "resources/data/output/ner/zh/ccks/address/0619/bert_biaffine/"
  do_lower_case: True
  device: cuda
